# This is a config for E2B sandbox template.
# You can use template ID (wv9m4185y64gc1399cj7) or template name (vibe-nextjs-templates-test-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-templates-test-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-templates-test-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-templates-test-2')

team_id = "2f583452-7d53-4b98-9920-77e4ca0a1f6d"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-templates-test-2"
template_id = "wv9m4185y64gc1399cj7"
